input {
  beats {
    id                          => "beats_tls_5044"
    port                        => 5044
    ssl_enabled                 => true
    ssl_certificate_authorities => ["/usr/share/logstash/certs/root-ca.pem"]
    ssl_certificate             => "/usr/share/logstash/certs/logstash.pem"
    ssl_key                     => "/usr/share/logstash/certs/logstash-key.pem"
    ssl_client_authentication   => "required"
    enrich                      => [source_metadata, ssl_peer_metadata]
    ecs_compatibility           => "v8"
  }
}

filter {
  if ![@metadata][input][beats][host][name] and [host] {
    mutate { copy => { "[host]" => "[@metadata][input][beats][host][name]" } }
  }
  mutate {
    add_field => {
      "[observer][vendor]" => "Netgate"
      "[labels][suru][ingest]" => "tier3-logstash"
    }
  }
  if [program] == "suricata" or [program] == "suricata-fast" {
    mutate { add_tag => ["route-suricata"] }
  } else if [program] =~ /^zeek-/ or [source_path] =~ /\/zeek\// {
    mutate { add_tag => ["route-zeek"] }
  } else if [program] =~ /^pfblockerng-/ {
    mutate { add_tag => ["route-pfblockerng"] }
  } else if [program] == "filterlog" {
    mutate { add_tag => ["route-pfsense-firewall"] }
  } else {
    mutate { add_tag => ["route-pfsense-services"] }
  }
}

output {
  if "route-suricata" in [tags] {
    pipeline { send_to => "suricata-eve-pipe" }
  } else if "route-zeek" in [tags] {
    pipeline { send_to => "zeek-pipe" }
  } else if "route-pfblockerng" in [tags] {
    pipeline { send_to => "pfblockerng-pipe" }
  } else if "route-pfsense-firewall" in [tags] {
    pipeline { send_to => "pfsense-firewall-pipe" }
  } else if "route-pfsense-services" in [tags] {
    pipeline { send_to => "pfsense-services-pipe" }
  } else {
    pipeline { send_to => "quarantine-pipe" }
  }
}
