# =============================================================================
# Pipeline : geoip (PASSTHROUGH — no enrichment)
# =============================================================================
# Used when no MaxMind GeoLite2 DB is present (MAXMIND_LICENSE_KEY unset). The
# logstash entrypoint copies THIS file to /tmp/geoip-pipeline/35-geoip.conf so
# events routed to geoip-pipe from 10/20/30 still reach OpenSearch — just
# without geo/ASN fields. Keeps ingestion healthy with geo disabled.
# Output block is identical to 35-geoip.conf (kept in lockstep).
# =============================================================================
input {
  pipeline { address => "geoip-pipe" }
}

output {
  if [event][module] == "suricata" {
    opensearch {
      ecs_compatibility => "v8"
      hosts    => ["https://${OPENSEARCH_HOST}:${OPENSEARCH_PORT}"]
      user     => "${OPENSEARCH_USER}"
      password => "${OPENSEARCH_PASSWORD}"
      ssl      => true
      cacert   => "/usr/share/logstash/certs/root-ca.pem"
      index    => "suru-suricata-%{+YYYY.MM.dd}"
    }
  } else if [event][module] == "zeek" {
    opensearch {
      ecs_compatibility => "v8"
      hosts    => ["https://${OPENSEARCH_HOST}:${OPENSEARCH_PORT}"]
      user     => "${OPENSEARCH_USER}"
      password => "${OPENSEARCH_PASSWORD}"
      ssl      => true
      cacert   => "/usr/share/logstash/certs/root-ca.pem"
      index    => "suru-zeek-%{+YYYY.MM.dd}"
    }
  } else {
    opensearch {
      ecs_compatibility => "v8"
      hosts    => ["https://${OPENSEARCH_HOST}:${OPENSEARCH_PORT}"]
      user     => "${OPENSEARCH_USER}"
      password => "${OPENSEARCH_PASSWORD}"
      ssl      => true
      cacert   => "/usr/share/logstash/certs/root-ca.pem"
      index    => "suru-pfsense-firewall-%{+YYYY.MM.dd}"
    }
  }
}
